### ISSUE TITLE
Expand error record

### ISSUE THREAD

**Issue by wwayne** [xavierchow/bunyan-logger-factory#2]
Original issue found in https://github.com/Wiredcraft/blue-internal/issues/149
seems bunyun can't record completed error info

**Comment by xavierchow** [comment]
explained here: https://github.com/Wiredcraft/blue-internal/issues/149, not an issue, just you need to adhere to the protocol defined by bunayn, closing.

**Comment by wwayne** [comment]
okay, I select using Winston 😂
